CREATE TABLE Users (
id  INTEGER  PRIMARY KEY  AUTO_INCREMENT ,
Email  VARCHAR(400),
PasswordHash  VARCHAR(400))

CREATE TABLE Articles (
Title  VARCHAR(400),
Content  VARCHAR(400),
Image  VARCHAR(400),
id  INTEGER  PRIMARY KEY  AUTO_INCREMENT )
