CREATE TABLE Users (
Email  VARCHAR(400),
PasswordHash  VARCHAR(400),
id  BIGINT PRIMARY KEY );

CREATE TABLE Articles (
id  BIGINT PRIMARY KEY ,
Title  VARCHAR(400),
Content  VARCHAR(400),
Image  VARCHAR(400));
